// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class ChatRoom
{
    public int ChatSid { get; set; }

    public int MemberSid { get; set; }

    public DateTime? ChatTime { get; set; }

    public string ChatContent { get; set; }

    public virtual Member MemberS { get; set; }
}