// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class DailyChickAmountsRate
{
    public string 會員名字 { get; set; }

    public string 雞舍位址 { get; set; }

    public string 雞舍名字 { get; set; }

    public string 生產種類 { get; set; }

    public DateOnly? 生產日期 { get; set; }

    public int? 剩餘雞隻 { get; set; }

    public double? DeathRate { get; set; }

    public double? EggRate { get; set; }

    public double? UnQrate { get; set; }

    public int? 生產數量 { get; set; }

    public int? 不合格數 { get; set; }

    public int? 死亡數 { get; set; }

    public int? WeekAge { get; set; }
}