// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class DailyChickAmountsRate
{
    public int? MemberSid { get; set; }

    public int? HouseSid { get; set; }

    public DateOnly? Date { get; set; }

    public int? RemainingCount { get; set; }

    public double? DeathRate { get; set; }

    public double? EggRate { get; set; }

    public double? UnQrate { get; set; }

    public int? EggAmount { get; set; }

    public int? UnQamount { get; set; }

    public int? SubcategoryNo { get; set; }
}