// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class EmpRank
{
    public int EmpRankSid { get; set; }

    public string EmpRank1 { get; set; }
}