// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EggProductionProject_MVC.Models
{
    public partial class GetEventsForMemberResult
    {
        public int id { get; set; }
        public string title { get; set; }
        public DateOnly? start { get; set; }
        public string DateStatus { get; set; }
        public string description { get; set; }
    }
}
