// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EggProductionProject_MVC.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EggProductionProject_MVC.Models
{
    public partial interface IEggPlatformContextProcedures
    {
        Task<List<GetDailyDataResult>> GetDailyDataAsync(int? Judge, int? MemberSid, int? HouseSid, string StartDate, string EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertCalendarAsync(int? MemberSid, string Title, string TodoList, DateOnly? StartDate, DateOnly? InsertDate, int? Finished, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
