// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class NormalizedDatum
{
    public int? Subcategory { get; set; }

    public int? WeekAge { get; set; }

    public double? EggRate { get; set; }

    public double? DeathRate { get; set; }
}