// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class OrderStatuses
{
    public int OrderStatusNo { get; set; }

    public string? OrderStatus { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}