// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class Payment
{
    public int PaymentNo { get; set; }

    public string Pay { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}