// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class ProductItem
{
    public int ItemNo { get; set; }

    public int? SubcategoryNo { get; set; }

    public string ItemName { get; set; }

    public string ItemDescription { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ProductSubcategory SubcategoryNoNavigation { get; set; }
}