// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EggProductionProject_MVC.Models;

public partial class StoreImage
{
    public int StoreImageSid { get; set; }

    public int? StoreSid { get; set; }

    public string ShopImagePath { get; set; }

    public string ImageDescription { get; set; }

    public DateTime? UploadTime { get; set; }

    public virtual Store StoreS { get; set; }
}