// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class ArticleCreater
{
    public int ArticleCreaterSid { get; set; }

    public int? MemberNo { get; set; }

    public string PersonalInfo { get; set; }

    public int? ArticleCount { get; set; }
}