// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class CarrierOpen
{
    public int CarrierOpenNo { get; set; }

    public int? StoreSid { get; set; }

    public int? StoreOpen { get; set; }

    public int? HouseOpen { get; set; }

    public virtual Store StoreS { get; set; }
}