// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class EcImage
{
    public int EcImgSid { get; set; }

    public byte[] EcImg { get; set; }

    public int? ProductSid { get; set; }

    public int? StoreSid { get; set; }

    public virtual Product ProductS { get; set; }

    public virtual Store StoreS { get; set; }
}