// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class FriendActionType
{
    public int ActionTypeSid { get; set; }

    public string ActionType { get; set; }

    public virtual ICollection<FriendAction> FriendActions { get; set; } = new List<FriendAction>();
}