// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class GoodorBad
{
    public int GorBsid { get; set; }

    public int? MemberNo { get; set; }

    public int? ArticleSid { get; set; }

    public int? ReplySid { get; set; }

    public DateOnly? GorBdate { get; set; }

    public int GorBtype { get; set; }

    public virtual Article ArticleS { get; set; }

    public virtual Member MemberNoNavigation { get; set; }

    public virtual Reply ReplyS { get; set; }
}