// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Log
{
    public int LogSid { get; set; }

    public int? MemberSid { get; set; }

    public byte? IsLogSuccess { get; set; }

    public DateTime? LogTime { get; set; }

    public virtual Member MemberS { get; set; }
}