// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class NotifyType
{
    public int NotifyTypeSid { get; set; }

    public string NotifyType1 { get; set; }

    public virtual ICollection<Notify> Notifies { get; set; } = new List<Notify>();
}