// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Notify
{
    public int NotifySid { get; set; }

    public int? NotifyRecieverid { get; set; }

    public int? NotifySenderid { get; set; }

    public int? WebSiteTypeSid { get; set; }

    public int? NotifyTypeSid { get; set; }

    public TimeOnly? NotifyTime { get; set; }

    public virtual Member NotifyReciever { get; set; }

    public virtual NotifyType NotifyTypeS { get; set; }

    public virtual WebSiteType WebSiteTypeS { get; set; }
}