// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class ShoppingRank
{
    public int ShoppingRankNo { get; set; }

    public string ShoppingRank1 { get; set; }

    public byte[] Eggimage { get; set; }

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();
}