// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class TrackTime
{
    public int TrackTimeSid { get; set; }

    public int? TrackSid { get; set; }

    public int? TrackStatusNo { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual Track TrackS { get; set; }

    public virtual TrackStatus TrackStatusNoNavigation { get; set; }
}