// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Vaccinate
{
    public int VaccinateSid { get; set; }

    public int ChickSid { get; set; }

    public string ChickLotNo { get; set; }

    public int VaccineSid { get; set; }

    public DateOnly VaccineDate { get; set; }

    public DateOnly VaccinateDate { get; set; }

    public virtual ChickLotNo ChickS { get; set; }

    public virtual VaccineTable VaccineS { get; set; }
}