// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class VaccineTable
{
    public int VaccineSid { get; set; }

    public string VaccineName { get; set; }

    public decimal Cost { get; set; }

    public virtual ICollection<Vaccinate> Vaccinates { get; set; } = new List<Vaccinate>();
}